project/authentication/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'authentication'
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.logout, name='logout'),
]

project/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('authentication.urls')),
    url(r'^', include('bankaccounts.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/authentication/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models

from extra.mixins import UUIDIdMixin

class AccountManager(BaseUserManager):
    def create_user(self, **kwargs):
        if not kwargs.get('email'):
            raise ValueError('Users must have a valid email address.')

        if not kwargs.get('password'):
            raise ValueError('Users must have a valid password.')

        account = self.model(
            email=self.normalize_email(kwargs.get('email', None)),
        )

        account.set_password(kwargs.get('password'))
        account.save()

        return account

    def create_superuser(self, **kwargs):
        account = self.create_user(**kwargs)

        account.is_admin = True
        account.save()

        return account

class Account(AbstractBaseUser, PermissionsMixin, UUIDIdMixin):
    email = models.EmailField(unique=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    is_admin = models.BooleanField(default=False)

    objects = AccountManager()

    USERNAME_FIELD = 'email'

    def __unicode__(self):
        return self.email

project/authentication/forms.py
from django import forms
from django.contrib.auth.password_validation import validate_password

from authentication.models import Account

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'id' : 'inputUsername',
                                                             'class' : 'form-control',
                                                             'placeholder' : 'Email',
                                                             'autocomplete' : 'off'}),
                                                             max_length=100)
    password= forms.CharField(widget=forms.PasswordInput(attrs={'id' : 'inputPassword',
                                                             'class' : 'form-control',
                                                             'placeholder' : 'Password'}))

class RegistrationForm(forms.ModelForm):

    email = forms.EmailField(widget=forms.TextInput(attrs={'id' : 'inputEmail',
                                                            'class' : 'form-control',
                                                            'placeholder' : 'Email',
                                                            'autocomplete' : 'off'}),
                                                            max_length=100)

    password = forms.CharField(widget=forms.PasswordInput(attrs={'id' : 'inputPassword',
                                                                'class' : 'form-control',
                                                                'placeholder' : 'Password'}))


    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'id' : 'inputConfirmPassword',
                                                                        'class' : 'form-control',
                                                                        'placeholder' : 'Confirm Password'}))
    class Meta:
        model = Account
        fields = ['email',
                'password',
                'confirm_password',
                ]

    def clean_email(self):
        email = self.cleaned_data['email']
        if Account.objects.filter(email=email).exists():
            raise forms.ValidationError('The Email, %s is already in use.' % email)
        return email

    def clean(self):
        """
        Checks if the passwords match
        """
        cleaned_data = super(RegistrationForm, self).clean()
        if 'password' in self.cleaned_data and 'confirm_password' in self.cleaned_data:
            if self.cleaned_data['password'] != self.cleaned_data['confirm_password']:
                raise forms.ValidationError("Passwords don't match. Please enter both fields again.")
            validate_password(self.cleaned_data.get('confirm_password'), self.instance)
        return self.cleaned_data

project/authentication/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.decorators import login_required

from models import Account
from forms import LoginForm, RegistrationForm

def register(request):
    if not request.user.is_authenticated():
        form = RegistrationForm()
        email = ''
        password = ''
        confirm_password = ''

        if request.method == 'POST':
            form = RegistrationForm(request.POST)
            if form.is_valid():
                email = form.cleaned_data['email']
                password = form.cleaned_data['password']
                confirm_password = form.cleaned_data['confirm_password']

                account = Account.objects.create_user(email=email, password=confirm_password)

                return redirect('authentication:login')

        context = {
                'form': form,
                'title':'Register',
        }

        return render(request, 'authentication/forms/register_form.html', context)
    else:
        return redirect('authentication:login', request.user.username)

def login(request):
    if not request.user.is_authenticated():
        form = LoginForm()
        username = ''
        password = ''
        state = ''
        if request.method == 'POST':
            form = LoginForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                user = authenticate(username=username, password=password)

                if user is not None:
                    if user.is_active:
                        auth_login(request, user)
                        return redirect('bankaccounts:index')
                    else:
                        state = "Your account is not active, please contact the administrator."
                else:
                    state = "Your username and/or password were incorrect."

        context = {
                'state': state,
                'username': username,
                'form': form,
                'title':'Login',
        }

        return render(request, 'authentication/forms/login_form.html', context)
    else:
        return redirect('bankaccounts:index')

@login_required
def logout(request):
    auth_logout(request)
    return redirect('authentication:login')

project/authentication/templates/authentication/forms/login_form.html
{% extends "authentication/base.html" %}
{% load staticfiles %}

{% block content %}
<!-- display the form -->
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Login</h3>
    </div>
    <form action='{% url 'authentication:login' %}' method="post" class="form">
        <fieldset>
            <div class="panel-body">
                {% csrf_token %}
                <div class="form-group">
                    {{ state }}
                </div>
                <div class="form-group">
                    {{ form.username }}
                </div>
                <div class="form-group">
                    {{ form.password }}
                </div>
                <button class="btn btn-primary btn-block" type='submit'>Sign in</button>
            </div>
        </fieldset>
    </form>
    <div class="panel-footer">
         <a class="" href="{% url 'authentication:register' %}">Register</a>
        <a href='#forgot password' class="">Forgot your password</a>
    </div>
</div>
{% endblock %}

project/authentication/templates/authentication/forms/register_form.html
{% extends "authentication/base.html" %}
{% load staticfiles %}

{% block content %}
<!-- display the form -->
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Register</h3>
    </div>
    <form action='{% url 'authentication:register' %}' method="post" class="form">
        <fieldset>
            <div class="panel-body">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {{ field }}
                        {% if form.errors %}
                            {% for error in field.errors %}
                                <small>{{ error|escape }}</small>
                            {% endfor %}
                        {% endif %}
                    </div>
                {% endfor %}

                <div class="form-group">
                    {% for error in form.non_field_errors %}
                        <small>{{ error|escape }}</small>
                    {% endfor %}
                </div>
                
                <button class="btn btn-primary btn-block" type='submit'>Register</button>
            </div>
            <div class="panel-footer">
                <a class="" href="{% url 'authentication:login' %}">Already have an account?</a>
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}