project/authentication/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'authentication'
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.logout, name='logout'),
]

project/config/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('authentication.urls')),
    url(r'^', include('bankaccounts.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/templates/europa/includes/footer.html
<!--footer-->
<footer>
    <div class="row">
        <div class="col-lg-12">
            <hr>
            <ul class="list-unstyled">
                <li class="pull-right"><a href="#top">Back to top</a></li>
                <li><a href="https://github.com/lazercube/europa/">GitHub</a></li>
                <li><a href="../help/#api">API</a></li>
                <li><a href="../help/#support">Support</a></li>
            </ul>
            <p>Europa. Created by Lazer</p>
            <p>Code released under the <a href="https://github.com/thomaspark/bootswatch/blob/gh-pages/LICENSE">MIT License</a>.</p>
            <p>Based on <a href="http://getbootstrap.com" rel="nofollow">Bootstrap</a>. Icons from <a href="http://fortawesome.github.io/Font-Awesome/" rel="nofollow">Font Awesome</a>. Web fonts from <a href="http://www.google.com/webfonts" rel="nofollow">Google</a>.</p>
        </div>
    </div>
</footer>
<!--endfooter-->

project/templates/europa/includes/header.html
<!--header-->
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
        <a href="/" class="navbar-brand">Europa</a>
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#navbar-main">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
            <ul class="nav navbar-nav">
                <li>
                    <a href="../help/">Help</a>
                </li>
                <li>
                    <a href="http://news.bootswatch.com">Blog</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href='{% url 'authentication:logout' %}'><i class="fa fa-sign-out" aria-hidden="true"></i>Sign Out</a></li>
            </ul>
        </div>
    </div>
</div>
<!--endheader-->